/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Wed May 02 14:43:21 CEST 2018
 */
package org.wildfly.camel.test.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Rating
 */
public enum Account_RatingEnum {

    // Cold
    COLD("Cold"),
    // Hot
    HOT("Hot"),
    // Warm
    WARM("Warm");

    final String value;

    private Account_RatingEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Account_RatingEnum fromValue(String value) {
        for (Account_RatingEnum e : Account_RatingEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
